# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hatchapp', '0002_auto_20160417_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
